enum board {
	BOARD_UNKNOWN = 0,
	BOARD_CAPTIVATE,
	BOARD_FASCINATE,
	BOARD_FASCINATE4G,
	BOARD_GALAXYS,
	BOARD_GALAXYS4G,
	BOARD_GALAXYSB,
	BOARD_VIBRANT,
	BOARD_WAVE2,
	BOARD_MAX,
};

extern enum board cur_board;
